Prevent mypy errors when a variable type is changed in `BaseISCSISR`
Log without this change on `chappasword` and `incoming_chappassword`:
```
error: Incompatible types in assignment (expression has type "bytes", variable has type "str")  [assignment]
```

Signed-off-by: Ronan Abhamon <ronan.abhamon@vates.fr>