fix(SR): add missing mypy annotations
Fix errors reported by mypy update (mypy-2.1.0) on our workflow.

In `SR.py` on `backends`:
```
drivers/SR.py:51: error: Need type annotation for "backends" (hint: "backends: list[<type>] = ...")  [var-annotated]
```

In `test_lock_queue.py`:
```
tests/test_lock_queue.py:15: error: Need type annotation for "saved_queue" (hint: "saved_queue: list[<type>] = ...")  [var-annotated]
```

Signed-off-by: Ronan Abhamon <ronan.abhamon@vates.tech>