Use `for session` instead of `for e`
Avoid mypy error:
```
error: Assignment to variable "e" outside except: block  [misc]
```

Signed-off-by: Ronan Abhamon <ronan.abhamon@vates.fr>